name: "🧪 test"

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        name: "🧪 test"
        runs-on: ubuntu-latest
        steps:
            - name: "📚 checkout"
              uses: actions/checkout@v3.5.3
            - name: "🟢 node"
              uses: actions/setup-node@v3.7.0
              with:
                  node-version: 19
                  registry-url: https://registry.npmjs.org/
            - name: "📦 install"
              run: npm ci
            - name: "🟦 types"
              run: npm run typecheck
            - name: "🧪 test"
              run: npm run test
            - name: "☂️ coverage"
              uses: codecov/codecov-action@v3.1.1
